# SPDX-FileCopyrightText: 2024 Alexandru Fikl <alexfikl@gmail.com>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "pyshocks"
SPDX-PackageSupplier = "Alexandru Fikl <alexfikl@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/alexfikl/pyshocks"

[[annotations]]
path = ["docs/*.rst", "docs/justfile", "scribbles/ss-weno.tex"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".readthedocs.yml",
    "justfile",
    "README.rst",
    "INSTALL.rst",
    "pyproject.toml",
    "requirements.txt",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [".gitignore", ".github/*.yml", ".github/workflows/*.yml", ".ci/requirements*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
